services:
  mongo:
    image: mongo:7.0
    environment:
      - MONGO_INITDB_ROOT_USERNAME=poker_mongo_app_user
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PWD}
    ports:
      - "27017:27017"
    networks:
      - poker-network

  postgres:
    image: postgres:16
    environment:
      - POSTGRES_USER=poker_postgres_app_user
      - POSTGRES_PASSWORD=${POSTGRES_PWD}
    ports:
      - "5432:5432"
    networks:
      - poker-network
  app:
    build:
      context: .
      dockerfile: ./Dockerfile  
    ports:
      - "8000:8000"
    depends_on:
      - mongo
      - postgres
    env_file:
      - .env
    environment:
      - MONGO_TEST_URI=mongodb://poker_mongo_app_user:${MONGO_PWD}@mongo:27017/pokerdbTest
      - MONGO_URI=mongodb://poker_mongo_app_user:${MONGO_PWD}@mongo:27017/pokerdb
      - POSTGRES_URI=postgresql+asyncpg://poker_postgres_app_user:${POSTGRES_PWD}@postgres:5432/pokerdb
      - POSTGRES_TEST_URI=postgresql+asyncpg://poker_postgres_app_user:${POSTGRES_PWD}@postgres:5432/pokerdbTest
      - USER_PWD=${USER_PWD}
    volumes:
      - ../:/home/pokerApp/development/pokerApp
    networks:
      - poker-network
networks:
  poker-network:
    driver: bridge